### ISSUE TITLE
'OutDegreeView' object has no attribute 'items'

### ISSUE THREAD

**Issue by cesarforteslima** [jackkamm/momi#2]
Dear popgenmethods,

I have the following issue. Thanks in advance for your reply.
Best regards,
Cesar

$ git clone https://github.com/popgenmethods/momi.git
$ cd momi
$ python tutorial.py 
Printing SFS entries for three epoch history
[3.46922568239798, 0.6905041803193086, 0.28925918566082426, 0.18382307646826954, 0.14630222131940324, 0.12951430246441245, 0.12025482991358812, 0.11413280441137114, 0.10950608451603584, 0.10569664740756339, 0.10239483376447593, 0.09944275368450997, 0.0967502566421602, 0.09426034418677022, 0.09193397689474075, 0.08974285562158904, 0.08766566223553252, 0.08568590655924462, 0.0837905841160356]

Printing truncated SFS for middle epoch
[0.1874478923928087, 0.08769197071896163, 0.05459923171604704, 0.038169703103527165, 0.028403412493141773, 0.021967054055764115, 0.017432083759685326, 0.014084243180327256, 0.011526734103605961, 0.009521488367390292, 0.007917017789540414, 0.0066123391320212456, 0.005537549081665744, 0.004642724239263062, 0.0038912611130865783, 0.003255713614919281, 0.00271509967519516, 0.0022531056531559686, 0.0018568577754385516]
Traceback (most recent call last):
  File "tutorial.py", line 46, in <module>
    demo3 = Demography.from_newick(newick_str)
  File "/media/cesarpc/momi/demography.py", line 13, in from_newick
    t = cls(_newick_to_nx(newick, default_lineages))
  File "/media/cesarpc/momi/demography.py", line 25, in __init__
    if not all('lineages' in nd[k] for k in self.leaves):
  File "/media/cesarpc/momi/util.py", line 44, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/media/cesarpc/momi/demography.py", line 66, in leaves
    return set([k for k, v in self.out_degree().items() if v == 0])
AttributeError: 'OutDegreeView' object has no attribute 'items'

**Comment by jackkamm** [comment]
Thanks for the report, I have fixed the bug and updated on pypi as well. Please let me know if you have any further problems.
